name: Upload to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Deploy Function
        id: sls-func
        uses: yc-actions/yc-sls-function@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          bucket: ${{ secrets.BUCKET }}
          folder-id: 'b1gac1g0nm3qptu01u57'
          function-name: 'mr-meme-note'
          service-account: 'github-tractor-robot'
          runtime: 'python312'
          memory: '128Mb'
          entrypoint: 'index.handler'
          secrets: |
            YA_GPT_API_TOKEN=e6qfdm5qdbbkgtm2p8ps/e6q8sjsdnks5gkvapcfd/YA_GPT_API_TOKEN
          include: |
            .
          exclude: |
            ./.git
            ./.github
